mpc_param_file: gazebo_scenario_params.yaml
ardrone0_init:
  x: [1.15,0,0.95, 1,0, 0.0,0.0, 0.0,0.0]
  xdes: [1.15,0,0.95, 1,0, 0.0,0.0, 0.0,0.0]
  # p: [-0.5092, 1.458, -1,1, -5, 1.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.3, 1.0] #without tracking position in cost function
  # p: [-0.5092, 1.458, -1,1, -5, 1.3, 5.0, 5.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.3, 1.0] #tracking position without orientation in cost function
  # p: [-0.5092, 1.458, -1,1, -5, 1.3, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.3, 1.0] #tracking orientation without position in cost function
  p: [-0.5092, 1.458, -1,1, -5, 1.3, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.3, 1.0] #tracking both orientation and position in cost function
  model: #vehicle 'linear' state model
    x: -0.5092
    z: 1.458
    xdot: -1
    zdot: 1
    y: -5
    ydot: 1.3
  Q: #state penalty
    x: 1.0
    y: 1.0
    z: 1.0
    phi: 1.0
  R: #input penalty
    ux: 1.0
    uy: 1.0
    uz: 0.3
    uphi: 1.0

  # double ardrone0_init_p[]={ //without tracking position
  #     -0.5092,1.458,-1,1,-5,1.3, //Model Parameters: Ardrone
  #     0.0,0.0,0.0, 0.0,0.0, 0.0,0.0,0.0,0.0, //State Penalty: no tracking
  #     x,y,z, 
  #     1.0,1.0,0.3,1.0 //Input penalty
  # };

constraint0_init:
  p: [1,0.17,0.5,1.5,1,1,1]

# the following are not implemented yet:
controller:
  HorizonDiskretization: 10
  HorizonLength: 1
  Tolerance: 1e-8
  UpdateIntervall: 0.01
  MaximumNumberofIterations: 10


